### ISSUE TITLE
Sveltefire require storage parameter?

### ISSUE THREAD

**Issue by socketopp** [codediodeio/sveltefire#144]
I get the following issue when using sveltefire. Anyone else experienced this?

<FirebaseApp {auth} {firestore}>

Property 'storage' is missing in type '{ auth: any; firestore: any; }' but required in type '{ firestore: Firestore; auth: Auth; storage: FirebaseStorage; }'.ts(2741)

**Comment by ItsAlexousd** [comment]
Hi @socketopp,

Currently, you need to initialize all Firebase services (auth, firestore and storage) even if you don't use them all. PR #130 fixes this problem, but we'll have to wait for @codediodeio to merge it.

**Comment by socketopp** [comment]
> Hi @socketopp,
> 
> Currently, you need to initialize all Firebase services (auth, firestore and storage) even if you don't use them all. PR #130 fixes this problem, but we'll have to wait for @codediodeio to merge it.

Thanks for the heads up. Currently using earlier version of Sveltefire that doesn't require. Will update once that once PR #130 is merged.
