### ISSUE TITLE
[ Q ] how to handle firebase keys/secrets?

### ISSUE THREAD

**Issue by DrMagPie** [codediodeio/sveltefire#20]
Hi,

I was exploring this project, and it looks very promising and cool. Thank you for your hard work. :)

But I have some security concerns, as Svelte compiles app into the static page it embeds all of the secrets into it. And they can be found in element inspector.
<img width="529" alt="Screenshot 2020-05-29 at 00 35 32" src="https://user-images.githubusercontent.com/23652900/83196452-99e52200-a144-11ea-8d59-9aae461b29ff.png">

And I can't find a solution to this issue.
Is there any best-practice? or suggestions/recommendations how to handle it?

if this question seems silly to you, then please bear with me. I'm not a developer so this whole stuff is very new to me :(

Thank you in advance.

**Comment by MichielLeyman** [comment]
Hi @DrMagPie 

Check out [this answer](https://stackoverflow.com/a/37484053) on Stackoverflow. Your firebase API keys are meant to public, it's how your project is identified on Google servers.

Firebase applications are secured through [security rules](https://firebase.google.com/docs/rules), which are important for you to set up.
I know it's counter-intuitive, but don't worry about the credentials.

**Comment by DrMagPie** [comment]
@MichielLeyman I see..., Thank you! and thanks for the references, it helps a lot.
