### ISSUE TITLE
Awaiting promises on user does not work

### ISSUE THREAD

**Issue by anmolsahoo25** [codediodeio/sveltefire#27]
Minimal code sample to reproduce the issue - 
```
<User let:user={user} persist={localStorage}>
  {#await user.getIdTokenResult()}
  {:then res}
  {/await}
</User>
```

This gives the error - `Uncaught TypeError: ctx[3].getIdTokenResult is not a function`

This works though - 
```
<User let:user={user} persist={localStorage}>
  <button on:click={() => console.log(user.getIdTokenResult)}>Click Me!</button>
</User>
```

Any ideas how I could debug this?

**Comment by anmolsahoo25** [comment]
Seems like the `user` object is not passed the methods of the `Firebase.Auth.User`. I am checking how this can be fixed.

**Comment by codediodeio** [comment]
`JSON.stringify` strips out the functions from the user object. Do you really need the `persist` option? The cached user should be replaced after the initial value, so this might work (untested)...

```
{ #if user.getIdTokenResult }

  {#await user.getIdTokenResult()}
  {:then res}
  {/await}

{ /if }
```

**Comment by anmolsahoo25** [comment]
Yep ended up going with something like this. Thank you!
