### ISSUE TITLE
Documentation:

### ISSUE THREAD

**Issue by Grynn** [codediodeio/sveltefire#3]
Hey,

This looks very interesting; I have not tinkered with Firebase in a while, so the following may be non-sense ...

How does Firebase Auth work? 

Example use case: I want to visit abc.com/admin; if not logged in, allow me to use Google / Github or similar oAuth creds to login. 

At the moment it looks like apiKeys are exposed to the client in `firebaseConfig`

```
const firebaseConfig = {
        apiKey: 'api-key',	//secret??
        authDomain: 'project-id.firebaseapp.com',
        databaseURL: 'https://project-id.firebaseio.com',
        projectId: 'project-id',
        storageBucket: 'project-id.appspot.com',
        messagingSenderId: 'sender-id',
        appId: 'app-id',
        measurementId: 'G-measurement-id',
    } 
```

Meaning the above code executes on the client right? Is there a way to do something like this:

client -> "serverless function": send auth token, get apiKey
"serverless function" -> client: apiKey valid for 30 mins? 

What can a user do with a Firebase api key?

Perhaps the serverless function can be used to proxy all calls to Firebase (where the serverless function has access to secrets like the apiKey, authDomain etc?)

**Comment by codediodeio** [comment]
The API keys just identify the project. You can authenticate requests with cloud functions, but a better approach is to use [Firebase Rules](https://firebase.google.com/docs/rules) to determine "what a user can do". For example, you could have a readonly database record with a prop of `admin: true`, then read it in the rules block reads to non-admin users.

**Comment by john--kane** [comment]
Hi Jeff,

I would love to re-use your svelte approach for a svelte lib I'm working on. Can you share the src/index.js file perchance? I didn't see it in the repo, unless its autogenerated?

Thanks :)

**Comment by codediodeio** [comment]
@john--kane good call, it was mistakenly in the .gitignore, fixed.

**Comment by john--kane** [comment]
> @john--kane good call, it was mistakenly in the .gitignore, fixed.

Legend, thanks :)
