### ISSUE TITLE
Nested <FirebaseApp>?

### ISSUE THREAD

**Issue by thinkloop** [codediodeio/sveltefire#38]
Can/should `<FirebaseApp>` be nested within child components? For example if a component has:

```
<FirebaseApp {firebase} perf analytics>
    <User let:user persist={localStorage}>
        <MyCustomComponent />
     </User>
</User>
```

Can `<MyCustomComponent />` also have `<FirebaseApp>` in it even though its parent has it?

**Comment by codediodeio** [comment]
Yes, this is possible but is unnecessary unless using multiple Firebase projects. The only purpose of `FirebaseApp` is to put the sdk into Svelte context.
