### ISSUE TITLE
Firebase App Already Exists

### ISSUE THREAD

**Issue by enricribas** [codediodeio/sveltefire#53]
Following the instructions here. 
https://github.com/codediodeio/sveltefire/blob/master/docs/install.md

The first time it works, but when I update Svelte files and HMR updates, I get an error 

> FirebaseError: Firebase: Firebase App named '[DEFAULT]' already exists (app/duplicate-app)

in the browser. Restarting the server works, but clearly not a fun process. 

Only difference is that there is no App.svelte file in latest SvelteKit, so I put my file in a __layout.svelte at the top level. 

The other thing is that this is SvelteKit not Svelte, so I tried placing the code in a `context="module"` as well as regular. 

Any ideas?

FYI: If I comment out the firebase.initializeApp command once it's running, it works.

**Comment by codediodeio** [comment]
If you get errors like this, the typically solution is to wrap the `initializeApp`in a try/catch. It's usually related to hot reloading with the dev server. 

```
try {
  initializeApp(...);
} catch (err) {
  if (!/already exists/u.test(err.message)) {
    console.error('Firebase Error: ', err)
  }
}
```
