### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by MarioDena** [codediodeio/sveltefire#62]
I see no changes in the last 2 years, is this project abandoned?

Or simply not being expanded anymore but working as intended?

I have problems using this and up-to-date imports (General errors, components not showing, firebase not getting data etc,)

Of course it may just be me, just want to be sure it's not a problem with this library.
Confirmation that this is no longer maintained and outdated would be appreciated.

**Comment by anokidev** [comment]
Probably abandoned. I will try to message jeff for this issue.

**Comment by CodeZwei** [comment]
Same, npm failed to build this correctly on a fresh checkout. I think the deps need to be greatly updated.

**Comment by fredguth** [comment]
There is another project that is based on this one that I know it is maintained: https://github.com/jacob-8/sveltefirets

**Comment by Tech-Helper503** [comment]
The deps that @codediodeio  are probably no longer supported or deprecated in this repo. The last commit was commit c2b045e55e74513977d4fdcf4b643a0f29179d27. On Jul, 10, 2020. Could @anokidev bring @codediodeio  into the discussion? Meanwhile, I'll fork this repo and update this issue

**Comment by codediodeio** [comment]
This project was in purgatory for awhile, but has now been updated to support Firebase v9 and TS, and is built with the new SvelteKit package tool.
