### ISSUE TITLE
"Firestore is not initialized" while using Sveltekit 

### ISSUE THREAD

**Issue by JBStepan** [codediodeio/sveltefire#95]
```svelte
<script>
    import { collectionStore, userStore } from "sveltefire";
    import { auth, firestore } from "../lib/firebase"
    import { GoogleAuthProvider, onAuthStateChanged, signInWithPopup } from "firebase/auth"

    const user = userStore(auth)

    async function login() {
        try {
            const provider = new GoogleAuthProvider();

            await signInWithPopup(auth, provider);

        } catch (e) {
            console.log(e);
        }
    }

    let entries = collectionStore(firestore, `users/${$user?.uid}/entries`, []);
    console.log(entries);
</script>

<main>
    <button on:click={login}>Login</button>

    {#each $entries as entry} 
        {entry.content}
    {/each}
</main>
```

This code when the tab is opened does not display the two documents that are in the collection.

The 3 entries do have content in them:
![image](https://github.com/codediodeio/sveltefire/assets/29986350/a91e07be-1eda-4171-a8cb-2f64a1569fbe)

But when the page loads it only shows the Login button:
![image](https://github.com/codediodeio/sveltefire/assets/29986350/9462a6c9-b26f-4c9c-8de6-01f8e4b03e52)

And the console says:
![image](https://github.com/codediodeio/sveltefire/assets/29986350/dd257387-6dcd-4285-85d5-6762952c42f0)

**Comment by caidanw** [comment]
It looks like your svelte component is being server side rendered. The Firebase SDK is meant for client side code, and I believe SvelteFire is meant only for the client side as well. So you'll need to turn off SSR for this component or the project as a whole.

You can turn off SSR by using this page option in `+page.js` ([docs](https://kit.svelte.dev/docs/page-options#ssr)):
```javascript
export const ssr = false;
```

Here are the errors in the code (notice the "Fallback for SSR"):
https://github.com/codediodeio/sveltefire/blob/388f1ef520f4486e6e4041d2174107b34bfed648/src/lib/stores.ts#L26
https://github.com/codediodeio/sveltefire/blob/388f1ef520f4486e6e4041d2174107b34bfed648/src/lib/stores.ts#L67
https://github.com/codediodeio/sveltefire/blob/388f1ef520f4486e6e4041d2174107b34bfed648/src/lib/stores.ts#L101

**Comment by codediodeio** [comment]
This issue is addressed in the latest release. The not-initialized warning is now separate avoid confusion.
