### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by chinmaykh** [codediodeio/sveltefire#97]
Is this project active? @codediodeio will you be releasing a 1.0? Asking since I want to use it in a project.

**Comment by codediodeio** [comment]
Yes. In fact, I am working with the Firebase team to get this package 100% solid. We'll be at 1.0 in the next couple months.

**Comment by chinmaykh** [comment]
Thanks for the update @codediodeio 
It's an honour to meet you. (Or at this point your AI clone). Watched your documentary, it was very interesting. Sorry for the spam.
